---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.mgmt.name }}-quay-wait-storagecluster-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.mgmt.name }}-quay-wait-storagecluster-job
          env:
          - name: SLEEP
            value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "ODF PreSync Hook"
              # set storage cluster name based on internal or external
              if [ {{ $.Values.mgmt.default_storage_class | quote }} = "ocs-storagecluster-ceph-rbd" ]; then
                STORAGE_NAME="ocs-storagecluster"
              else
                STORAGE_NAME="ocs-external-storagecluster"
              fi
              CSV_STATUS="Pausing $SLEEP seconds..."
              while [ "$CSV_STATUS" != "Ready" ]; do
                echo "Waiting for the ODF Operator to be ready. ($CSV_STATUS)"
                sleep $SLEEP
                CSV_STATUS=$( oc get -n openshift-storage StorageCluster $STORAGE_NAME -o jsonpath={..status.phase} )
              done
              echo "All done! Hooray!"
