---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.global.gitops.service_account }}-acm-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.global.gitops.service_account }}
    namespace: open-cluster-management
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.global.gitops.service_account }}
  namespace: open-cluster-management
#