---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: {{ $.Values.mgmt.ai.service_config_name }}
  name: agent
  namespace: multicluster-engine
spec:
  databaseStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
  filesystemStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  mirrorRegistryRef:
    name: mirror-registry-config-map
  osImages:
    - openshiftVersion: {{ $.Values.mgmt.ai.os_images.osp_version | quote }}
      version: {{ $.Values.mgmt.ai.os_images.rhcos_version | quote }}
      cpuArchitecture: x86_64
      rootFSUrl: >-
        {{ $.Values.mgmt.ai.os_images.root_fs_img_url }}
      url: >-
        {{ $.Values.mgmt.ai.os_images.root_fs_iso_url }}
