---
kind: Secret
apiVersion: v1
metadata:
  name: repo-{{ $.Values.git_url }}
  namespace: {{ $.Values.global.gitops.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  password: {{ coalesce $.Values.mgmt.git_token $.Values.global.git_token | b64enc }}
  type: Z2l0
  url: {{ printf "%s/cluster-%s.git" $.Values.global.git_cluster_prefix_url $.Values.git_url | b64enc | indent 2 }}
  username: {{ coalesce $.Values.mgmt.git_user $.Values.global.git_user | b64enc }}
type: Opaque



