{{- if $.Values.mgmt.git_user_clusters -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: repo-{{ $.Values.git_url }}
  namespace: {{ $.Values.global.gitops.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  password: {{ $.Values.mgmt.git_token_clusters | b64enc }}
  type: Z2l0
  url: {{ printf "%s/cluster-%s.git" $.Values.mgmt.git_prefix_url_clusters $.Values.git_url | b64enc | indent 2 }}
  username: {{ $.Values.mgmt.git_user_clusters | b64enc }}
  insecure: dHJ1ZQ==
type: Opaque
{{- end -}}
