---
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: noobaa
  namespace: openshift-storage
spec:
  coreResources:
    limits:
      cpu: '1'
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 4Gi
  dbResources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi
  dbType: postgres
  dbVolumeResources:
    requests:
      storage: 50Gi
  defaultBackingStoreSpec:
    pvPool:
      numVolumes: 5
      resources:
        requests:
          storage: 50Gi 
      storageClass: {{ $.Values.mgmt.default_storage_class | quote }}
    type: pv-pool
