apiVersion: v1
data:
  thanos.yaml: {{ $.Values.mgmt.acm.thanos_yaml | b64enc | indent 2 }}
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability  
type: Opaque
