---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.mgmt.name }}-quay-wait-storagecluster-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.mgmt.name }}-quay-wait-storagecluster-job
          env:
          - name: SLEEP
            value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "Qauy PreSync Hook"
              echo "Waiting for Noobaa storage class"
              while ! `oc get storageclass | egrep openshift-storage.noobaa.io -q`; do
                sleep $SLEEP;
              done
              echo "All done! Hooray!"
              sleep 15
