---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.mgmt.name }}-add-pull-secret-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.mgmt.name }}-add-pull-secret-job
          command:
            - /bin/bash
            - -c
            - |
              echo "Adding local pull secret to the global one."
              if [ {{ $.Values.mgmt.registry.url | quote }} = "" ]; then
                echo "Nothing to do as there is no local reigstry."
              else
                host_fqdn={{ $.Values.mgmt.registry.url | quote}}
                b64auth=$( echo -n '{{ $.Values.mgmt.registry.user }}:{{ $.Values.mgmt.registry.password }}' | openssl base64 )
                oc get secret pull-secret -n openshift-config --template='{{ "{{" }}index .data ".dockerconfigjson" | base64decode{{ "}}" }}' > /tmp/ps.json
{{- range $.Values.mgmt.registry.orgs }}
                AUTHSTRING="{\"$host_fqdn/{{ .name }}\": {\"auth\": \"$b64auth\",\"email\": \"\"}}"
                jq -c ".auths += $AUTHSTRING" < /tmp/ps.json > /tmp/ps-tmp.json
                mv -f /tmp/ps-tmp.json /tmp/ps.json
{{- end }}
                oc set data secret secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=/tmp/ps.json
              fi
              rm -f /tmp/ps.json
              echo "All done! Hooray!"
              sleep 30

