---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  name: preinstall-{{ $.Values.mgmt.name }}-wait-cnv-prepare-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.mgmt.name }}-wait-cnv-prepare-job
          env:
          - name: SLEEP
            value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "CNV PreSync Hook"
              while :
              do
                echo "Waiting for CNV CRDs. ($INSTALL_STATUS)"
                sleep $SLEEP
                if `oc get crd | egrep -i HyperConverged -q`
                then break
                fi
              done
              echo "All done! Hooray!"
