---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.mgmt.name }}-ai-wait-storagecluster-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.mgmt.name }}-ai-wait-storagecluster-job
          env:
          - name: SLEEP
            value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "AI PreSync Hook"
              # set storage cluster name based on internal or external
              LVM_STATUS="Pausing $SLEEP seconds..."
              while [ "$LVM_STATUS" != "Ready" ]; do
                echo "Waiting for the ODF Operator to be ready. ($LVM_STATUS)"
                sleep $SLEEP
                LVM_STATUS=$( oc get -n openshift-storage LVMCluster lvmcluster-manage -o jsonpath={..status.deviceClassStatuses..nodeStatus..status} )
              done
              echo "All done! Hooray!"
