---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: ocpmgmt-repo
spec:
  repositoryDigestMirrors:
  - mirrors:
    - "{{ $.Values.mgmt.registry.url }}/{{ $.Values.mgmt.registry.user }}/{{ $.Values.mgmt.registry.path }}"
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - "{{ $.Values.mgmt.registry.url }}/{{ $.Values.mgmt.registry.user }}/{{ $.Values.mgmt.registry.path }}"
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
