apiVersion: observability.open-cluster-management.io/v1beta1
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  availabilityConfig: High 
  enableDownSampling: false
  imagePullPolicy: Always
  observabilityAddonSpec:
    enableMetrics: true 
    interval: 30
  retentionResolution1h: 30d
  retentionResolution5m: 14d
  retentionResolutionRaw: 5d
  storageConfigObject:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
    statefulSetSize: 10Gi
    statefulSetStorageClass: gp2
  RetentionConfig:
    retentionInLocal: 24h