---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: postinstall-{{ $.Values.mgmt.name }}-wait-default-storageclass-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.mgmt.name }}-wait-default-storageclass-job
          env:
            - name: SLEEP
              value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "ODF PostSync Hook"
              DEFAULT_CLASS={{ $.Values.mgmt.default_storage_class }}
              ODF_CLASS="Pausing $SLEEP seconds..."
              while [ "$ODF_CLASS" != "$DEFAULT_CLASS" ]; do
                echo "Waiting for the ODF Storage Class to be ready. ($ODF_CLASS)"
                sleep $SLEEP
                ODF_CLASS=$( oc get storageclass | egrep $DEFAULT_CLASS | awk '{print $1}' )
              done
              oc patch storageclass $DEFAULT_CLASS -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
              echo "All done! Hooray!"
