---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odf-registry
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: odf-storagecluster-cephfs
