---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: presync-set-global-pull-secret-job
  namespace: open-cluster-management
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: set-global-pull-secret-job
          env:
            - name: SLEEP
              value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "Create global pull secret if needed"
              sleep $SLEEP
              if [ {{ $.Values.mgmt.registry.url | quote }} = "" ]; then
                oc get secret pull-secret -n openshift-config --template='{{ "{{" }}index .data ".dockerconfigjson" | base64decode{{ "}}" }}' > /tmp/ps.json
                oc --as=cluster-admin create secret generic {{ $.Values.global.ai.pull_secret_name }} -n open-cluster-management --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=/tmp/ps.json
              else
                host_fqdn={{ $.Values.mgmt.registry.url | quote}}
                b64auth=$( echo -n '{{ $.Values.mgmt.registry.user }}:{{ $.Values.mgmt.registry.password }}' | openssl base64 )
                oc get secret pull-secret -n openshift-config --template='{{ "{{" }}index .data ".dockerconfigjson" | base64decode{{ "}}" }}' > /tmp/ps.json
                AUTHSTRING="{\"$host_fqdn\": {\"auth\": \"$b64auth\",\"email\": \"\"}}"
                jq -c ".auths += $AUTHSTRING" < /tmp/ps.json > /tmp/ps-tmp.json
                mv -f /tmp/ps-tmp.json /tmp/ps.json
{{- range $.Values.mgmt.registry.orgs }}
                AUTHSTRING="{\"$host_fqdn/{{ .name }}\": {\"auth\": \"$b64auth\",\"email\": \"\"}}"
                jq -c ".auths += $AUTHSTRING" < /tmp/ps.json > /tmp/ps-tmp.json
                mv -f /tmp/ps-tmp.json /tmp/ps.json
                #cat /tmp/ps.json
{{- end }}
                oc --as=cluster-admin delete secret {{ $.Values.global.ai.pull_secret_name }} -n open-cluster-management
                oc --as=cluster-admin create secret generic {{ $.Values.global.ai.pull_secret_name }} -n open-cluster-management --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=/tmp/ps.json
              fi
              rm -f /tmp/ps.json
              rm -f /tmp/ps.json
              echo "All done! Hooray!"
              sleep 30
