---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.mgmt.name }}-csv-wait-acm-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.mgmt.name }}-csv-wait-acm-job
          env:
          - name: SLEEP
            value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "LVM-Operator PreInstall Hook"
              CSV_NAME=$(oc get csv -n open-cluster-management  | egrep open-cluster-management | awk '{print $1}')
              CSV_STATUS="Pausing $SLEEP seconds..."
              while [ "$CSV_STATUS" != "InstallSucceeded" ]; do
                echo "Waiting for the ACM Operator to be ready. ($CSV_STATUS)"
                sleep $SLEEP
                #CSV_STATUS=$( oc get csv -n open-cluster-management $CSV_NAME -o jsonpath={..status.conditions[-1:].reason} )
                #For some reason the job returnes multiple "InstallSucceede"
                CSV_STATUS=$( oc get csv -n open-cluster-management $CSV_NAME -o jsonpath={..status.conditions[-1:]} | jq .| egrep reason | tail -1 | awk -F '"' '{print $4}' )
              done
              echo "All done! Hooray!"