---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.mgmt.name }}-add-pull-secret-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.mgmt.name }}-add-pull-secret-job
          command:
            - /bin/bash
            - -c
            - |
              echo "Adding local pull secret to the global one."
              cd /tmp
              oc extract secret/pull-secret -n openshift-config --confirm
              cat .dockerconfigjson | \
                  jq --compact-output '.auths["{{ coalesce $.Values.mgmt.registry.url $.Values.global.registry.url }}/{{ coalesce $.Values.mgmt.registry.user $.Values.global.registry.user }}"] |= . + {"auth":"{{ printf "%s:%s" ( coalesce $.Values.mgmt.registry.user $.Values.global.registry.user ) ( coalesce $.Values.mgmt.registry.password $.Values.global.registry.password ) | b64enc  }}"}' \
                  > new_dockerconfigjson
              oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=new_dockerconfigjson
              rm -f .dockerconfigjson new_dockerconfigjson
              echo "All done! Hooray!"
#

