kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-ca-local
  namespace: openshift-config
data:
  {{ $.Values.mgmt.registry.url }}: {{ toYaml $.Values.global.ai.ca | indent 2 }}
  updateservice-registry: {{ toYaml $.Values.global.ai.ca | indent 2 }}