kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-ca-local
  namespace: openshift-config
data:
  {{ coalesce $.Values.mgmt.registry.url $.Values.global.registry.url }}: {{ toYaml $.Values.global.ai.ca | indent 2 }}
  