---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: {{ $.Values.mgmt.name }}-{{ $.Values.global.gitops.namespace }}-operators-config
 namespace: {{ $.Values.global.gitops.namespace }}
spec:
  generators:
    - git:
        repoURL: '{{ $.Values.mgmt.git_url }}'
        directories:
          - path: bp-mgmt/operators-config/*
        revision: HEAD
  template:
    metadata:
      name: '01-{{ $.Values.mgmt.name }}-config-{{ "{{" }}path.basename{{ "}}" }}'
      namespace: {{ $.Values.global.gitops.namespace }}
    spec:
      ignoreDifferences:
      - group: "*"
        kind: Secret
        jsonPointers:
        - /data/config.yaml
      - group: "*"
        kind: QuayRegistry
        jsonPointers:
        - /spec/configBundleSecret
      - group: '*'
        kind: QuayRegistry
        jsonPointers:
        - /spec/components
      destination:
        namespace: {{ $.Values.global.gitops.namespace }}
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: '{{ $.Values.mgmt.git_url }}'
        path: '{{ "{{" }}path{{ "}}" }}'
        targetRevision: HEAD
        helm:
          valueFiles:
            - "{{ $.Values.global.values_location }}"
            - "{{ $.Values.mgmt.values_location }}"
